name: seysmoprognoz
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  google_fonts: ^5.1.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  pull_to_refresh: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  flutter_svg: ^2.0.7
  toggle_switch: ^2.1.0
  google_maps_flutter: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  shimmer: ^2.0.0 
  freezed: ^2.3.4
  dio: ^4.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  smooth_page_indicator: ^1.1.0
  easy_localization: ^3.0.1
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  background_fetch: ^1.2.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true 
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash.png
  android_12:
    image: assets/icons/splash.png