// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5reukaNj7W3tuchu3ert5xD_AIsGX5o',
    appId: '1:604524100780:android:6e84028d3dd63ad7867309',
    messagingSenderId: '604524100780',
    projectId: 'smrm-421b6',
    databaseURL: 'https://smrm-421b6.firebaseio.com',
    storageBucket: 'smrm-421b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWijJ-iTE-2hXV3zo6Pn32y4jM2WCPe8s',
    appId: '1:604524100780:ios:c376e98767462a2e867309',
    messagingSenderId: '604524100780',
    projectId: 'smrm-421b6',
    databaseURL: 'https://smrm-421b6.firebaseio.com',
    storageBucket: 'smrm-421b6.appspot.com',
    androidClientId: '604524100780-6r28cmjc9901o7uo3p5sijgs3ebvic4m.apps.googleusercontent.com',
    iosClientId: '604524100780-n3rqbhajk5psnciqjvr717qrlgcos3g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.seysmoprognoz',
  );
}
